### ISSUE TITLE
Incorrect reference

### ISSUE THREAD

**Issue by riannek** [chrisdfong/Gender-Pay-Gap-Analysis#1]
Hi, 
I'm trying out the Project.ipynb. I had to change a few variables to get it to work. 
At the 'Summary Tables' : 
`mydata = [[male_mean], [female_mean], [gap], [endowments], [coefficients], [interaction]]`
instead of 
`mydata = [[group1], [group2], [difference], [endowments], [coefficients], [interaction]]`

and similarly: 
`mydata = [[male_mean], [female_mean], [gap], [explained], [unexplained]]`
instead of 
`mydata = [[group1], [group2], [difference], [explained], [unexplained]]`

The only thing I can't figure out is what `'cfs'` should be in : 
`mydata = [[co] for co in cfs]`

Could you help me out ? Thanks!

**Comment by TomPiona** [comment]
Thanks for catching that! I copied and pasted and forgot a cell from another notebook and forgot to change the variable names. The assignment line for `cfs` is also in the notebook now!
